name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools==65.5.0
        pip install pytest flask bs4 pandas

    - name: Test with pytest
      run: |
        pytest

    - name: Build Docker image
      run: |
        docker build -t data-masking-app -f data_masking_app/Dockerfile .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag data-masking-app:latest ${{ secrets.DOCKER_USERNAME }}/data-masking-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/data-masking-app:latest
